# This here is a database of GDScript parser and compiler error messages and warnings.
# We use it to create a mapping between identifiable messages and some abstract codes which we
# can refer to internally.
#
# Warnings are already provided by codes, so we can just use an enum exactly like it is defined
# in the engine.
#
# Errors on the other hand are harder. There are two groups of errors, parser errors and compiler
# errors. There is only a few compiler errors, but around 300 well defined parser errors, with
# additional possibility for generic parser errors.
#
# Each error is received with a generic code (-1), and can only be identified by its message
# contents. We store those messages (cleaned up for better maintainability) as is, but we don't
# actually use the raw messages for anything. Instead, each noteworthy message is assigned a
# number of text snippets which are unique to it. These snippets are then used to figure out
# which message was generated. When we successfully identified the message, we give it
# a code from the enum below. That code is then used to fetch our custom error explanation,
# translation, etc. Multiple raw messages can share the same code.
#
class_name GDScriptCodes
extends RefCounted

# Codes start at 10000 to give some space for WarningCodes coming from the engine.
enum ErrorCode {
	NONEXISTENT_IDENTIFIER = 10000,
	TYPE_CANNOT_BE_INFERRED,
	CYCLIC_REFERENCE,
	MISPLACED_KEYWORD,
	INVALID_ARGUMENTS,
	MISPLACED_IDENTIFIER,
	ASSIGNING_TO_EXPRESSION,
	STANDALONE_EXPRESSION,
	UNEXPECTED_EOL,
	EXPECTED_CONSTANT_EXPRESSION,
	SHADOWED_VARIABLE,
	INVALID_CLASS_DECLARATION,
	DUPLICATE_DECLARATION,
	MISPLACED_TYPE_IDENTIFIER,
	UNEXPECTED_CHARACTER_IN_KEYWORD,
	DEPRECATED_KEYWORD,
	UNEXPECTED_CHARACTER,
	INVALID_INDENTATION,
	DUPLICATE_SIGNAL_DECLARATION,
	MISPLACED_STATIC_CALL,
	RETURN_VALUE_MISMATCH,
	IN_EXPECTED_AFTER_IDENTIFIER,
	INVALID_OPERATOR_USAGE,
	TYPE_MISMATCH,
	INCOMPATIBLE_TERNARY,
	SIGNATURE_MISMATCH,
	CANT_ASSIGN_TO_CONSTANT,
	VOID_ASSIGNMENT,
	UNSAFE_METHOD_ACCESS,
	FUNCTION_USED_AS_PROPERTY,
	PROPERTY_USED_AS_FUNCTION,
	FUNCTION_MAY_YIELD,
	UNSAFE_CAST,
	UNSAFE_PROPERTY_ACCESS,
	UNASSIGNED_VARIABLE,
	CANT_GET_INDEX,
	UNKNOWN_CHARACTER,
	SPACES_BEFORE_TABS,
}

enum WarningCode {
	UNASSIGNED_VARIABLE, # Variable used but never assigned.
	UNASSIGNED_VARIABLE_OP_ASSIGN, # Variable never assigned but used in an assignment operation (+=, *=, etc).
	UNUSED_VARIABLE, # Local variable is declared but never used.
	SHADOWED_VARIABLE, # Variable name shadowed by other variable.
	UNUSED_CLASS_VARIABLE, # Class variable is declared but never used in the file.
	UNUSED_ARGUMENT, # Function argument is never used.
	UNREACHABLE_CODE, # Code after a return statement.
	STANDALONE_EXPRESSION, # Expression not assigned to a variable.
	VOID_ASSIGNMENT, # Function returns void but it's assigned to a variable.
	NARROWING_CONVERSION, # Float value into an integer slot, precision is lost.
	FUNCTION_MAY_YIELD, # Typed assign of function call that yields (it may return a function state).
	VARIABLE_CONFLICTS_FUNCTION, # Variable has the same name of a function.
	FUNCTION_CONFLICTS_VARIABLE, # Function has the same name of a variable.
	FUNCTION_CONFLICTS_CONSTANT, # Function has the same name of a constant.
	INCOMPATIBLE_TERNARY, # Possible values of a ternary if are not mutually compatible.
	UNUSED_SIGNAL, # Signal is defined but never emitted.
	RETURN_VALUE_DISCARDED, # Function call returns something but the value isn't used.
	PROPERTY_USED_AS_FUNCTION, # Function not found, but there's a property with the same name.
	CONSTANT_USED_AS_FUNCTION, # Function not found, but there's a constant with the same name.
	FUNCTION_USED_AS_PROPERTY, # Property not found, but there's a function with the same name.
	INTEGER_DIVISION, # Integer divide by integer, decimal part is discarded.
	UNSAFE_PROPERTY_ACCESS, # Property not found in the detected type (but can be in subtypes).
	UNSAFE_METHOD_ACCESS, # Function not found in the detected type (but can be in subtypes).
	UNSAFE_CAST, # Cast used in an unknown type.
	UNSAFE_CALL_ARGUMENT, # Function call argument is of a supertype of the require argument.
	DEPRECATED_KEYWORD, # The keyword is deprecated and should be replaced.
	STANDALONE_TERNARY, # Return value of ternary expression is discarded.
}

# The database of error messages from GDScript parser and compiler.
#
# Each item is a record mapping patterns to an error code that we introduce above.
# Items with "_unused" field are there to store messages that we didn't classify (yet).
# The entire list is split into compiler and parser errors for our own convenience.
# The "raw" field is unused and exists for reference when defining patterns.
# Multiple items can return the same error code, if that helps organization and maintenance.
#
# Valid records have the following structure:
#{
#	"patterns": [], # Array of Array of String
#	"raw": [], # Array of String
#	"code": -1, # ErrorCode
#}
#
# You can test validity of this database by running res://tests/TestGDScriptCodes.gd
#
const MESSAGE_DATABASE := [
	{
		"patterns": [
			["GDScript bug (please report): Native class \"", "\" not found.", ],
			["Could not find script \"", "\": ", ],
			["Could not find class \"", "\" in \"", "\".", ],
			["Identifier not found: ", ],
			["Failed to compile depended scripts.", ],
			["Unrecognized annotation: \"", "\".", ],
			["Invalid warning name: \"", "\".", ],
			["Could not parse script \"", "\": ", ".", ],
			["Could not resolve super class path \"", "\".", ],
			["Could not resolve super class \"", "\".", ],
			["Could not parse singleton from \"", "\".", ],
			["Could not find base class \"", "\".", ],
			["Could not find nested type \"", "\".", ],
			["Identifier \"", "\" is not a preloaded script or class.", ],
			["Could not parse script from \"", "\".", ],
			["Name \"", "\" is not a nested type of \"Variant\".", ],
			["Name \"", "\" is not a nested type of \"", "\".", ],
			["Could not parse global class \"", "\" from \"", "\".", ],
			["The referenced autoload \"", "\" (from \"", "\") could not be loaded.", ],
			["Could not parse singleton \"", "\" from \"", "\".", ],
			["Could not parse script from \"", "\".", ],
			["Could not find type \"", "\" in the current scope.", ],
			["Could not find type \"", "\" under base \"", "\".", ],
			["Could not find type \"", "\" in \"", "\".", ],
			["Could not find nested type \"", "\" under base \"", "\".", ],
			["Could not parse script \"", "\": ", " (While resolving external class member \"", "\").", ],
			["Could not resolve external class member \"", "\".", ],
			["Could not resolve class \"", "\".", ],
			["Getter \"", "\" not found.", ],
			["Setter \"", "\" not found.", ],
			["Could not find script for class \"", "\".", ],
			["Could not resolve class \"", "\", because of a parser error.", ],
			["Parser bug (please report): Could not find external parser for class \"", "\". (", ")", ],
			["Error while getting cache for script \"", "\".", ],
			["Identifier \"", "\" not declared in the current scope.", ],
			["Identifier \"", "\" not declared in the current scope.", ],
			["Preload file \"", "\" has no resource loaders (unrecognized file extension).", ],
			["Preload file \"", "\" does not exist.", ],
			["Could not preload resource script \"", "\".", ],
			["Could not preload resource file \"", "\".", ],
			["Could not find script \"", "\".", ],
			["Could not resolve script \"", "\".", ],
			["Native class ", " used in script doesn't exist or isn't exposed.", ],
		],
		"raw": [
			"GDScript bug (please report): Native class \"%IDENTIFIER%\" not found.",
			"Could not find script \"%PATH%\": %ERROR_NAME%",
			"Could not find class \"%IDENTIFIER%\" in \"%PATH%\".",
			"Identifier not found: %IDENTIFIER%",
			"Failed to compile depended scripts.",
			"Unrecognized annotation: \"%NAME%\".",
			"Invalid warning name: \"%WARNING%\".",
			"Could not parse script \"%SCRIPT_PATH%\": %ERROR_NAME%.",
			"Could not resolve super class path \"%EXTENDS_PATH%\".",
			"Could not resolve super class \"%NAME%\".",
			"Could not parse singleton from \"%PATH%\".",
			"Could not find base class \"%NAME%\".",
			"Could not find nested type \"%NAME%\".",
			"Identifier \"%NAME%\" is not a preloaded script or class.",
			"Could not parse script from \"%PATH%\".",
			"Name \"%ENUM_NAME%\" is not a nested type of \"Variant\".",
			"Name \"%ENUM_NAME%\" is not a nested type of \"%CLASS%\".",
			"Could not parse global class \"%CLASS%\" from \"%CLASS_PATH%\".",
			"The referenced autoload \"%CLASS%\" (from \"%SCRIPT_PATH%\") could not be loaded.",
			"Could not parse singleton \"%CLASS%\" from \"%SCRIPT_PATH%\".",
			"Could not parse script from \"%SCRIPT_PATH%\".",
			"Could not find type \"%IDENTIFIER%\" in the current scope.",
			"Could not find type \"%NAME%\" under base \"%NAME%\".",
			"Could not find type \"%NAME%\" in \"%IDENTIFIER%\".",
			"Could not find nested type \"%NAME%\" under base \"%NAME%\".",
			"Could not parse script \"%SCRIPT_PATH%\": %ERROR_NAME% (While resolving external class member \"%NAME%\").",
			"Could not resolve external class member \"%NAME%\".",
			"Could not resolve class \"%FQCN%\".",
			"Getter \"%NAME%\" not found.",
			"Setter \"%NAME%\" not found.",
			"Could not find script for class \"%CLASS_NAME%\".",
			"Could not resolve class \"%CLASS_NAME%\", because of a parser error.",
			"Parser bug (please report): Could not find external parser for class \"%FQCN%\". (%CONTEXT%)",
			"Error while getting cache for script \"%SCRIPT_PATH%\".",
			"Identifier \"%NAME%\" not declared in the current scope.%RENAME_HINT%",
			"Identifier \"%NAME%\" not declared in the current scope.",
			"Preload file \"%RESOLVED_PATH%\" has no resource loaders (unrecognized file extension).",
			"Preload file \"%RESOLVED_PATH%\" does not exist.",
			"Could not preload resource script \"%RESOLVED_PATH%\".",
			"Could not preload resource file \"%RESOLVED_PATH%\".",
			"Could not find script \"%SCRIPT_PATH%\".",
			"Could not resolve script \"%SCRIPT_PATH%\".",
			"Native class %BASE_NATIVE% used in script doesn't exist or isn't exposed.",
		],
		"code": ErrorCode.NONEXISTENT_IDENTIFIER,
	},
	{
		"patterns": [
			["Parser bug (please report): converting unresolved type.", ],
			["Cannot use simple \"@export\" annotation with variable without type or initializer, since type can't be inferred.", ],
			["Cannot use simple \"@export\" annotation because the type of the initialized value can't be inferred.", ],
			["Cannot infer the type of \"", "\" ", " because the value doesn't have a set type.", ],
			["Cannot infer the type of \"", "\" ", " because the value is \"null\".", ],
			["Could not resolve type for ", " \"", "\".", ],
		],
		"raw": [
			"Parser bug (please report): converting unresolved type.",
			"Cannot use simple \"@export\" annotation with variable without type or initializer, since type can't be inferred.",
			"Cannot use simple \"@export\" annotation because the type of the initialized value can't be inferred.",
			"Cannot infer the type of \"%NAME%\" %KIND% because the value doesn't have a set type.",
			"Cannot infer the type of \"%NAME%\" %KIND% because the value is \"null\".",
			"Could not resolve type for %KIND% \"%NAME%\".",
		],
		"code": ErrorCode.TYPE_CANNOT_BE_INFERRED,
	},
	{
		"patterns": [
			["Can't load global class ", ", cyclic reference?", ],
			["Cyclic class reference for \"", "\".", ],
			["Could not resolve class \"", "\": Cyclic reference.", ],
			["Cyclic inheritance.", ],
			["Could not resolve datatype: Cyclic reference.", ],
			["Could not resolve member \"", "\": Cyclic reference.", ],
			["Could not resolve function \"", "\": Cyclic reference.", ],
		],
		"raw": [
			"Can't load global class %IDENTIFIER%, cyclic reference?",
			"Cyclic class reference for \"%IDENTIFIER%\".",
			"Could not resolve class \"%IDENTIFIER%\": Cyclic reference.",
			"Cyclic inheritance.",
			"Could not resolve datatype: Cyclic reference.",
			"Could not resolve member \"%NAME%\": Cyclic reference.",
			"Could not resolve function \"%FUNCTION_NAME%\": Cyclic reference.",
		],
		"code": ErrorCode.CYCLIC_REFERENCE,
	},
	{
		"patterns": [
			["'self' not present in static function.", ],
			["Cannot use \"break\" outside of a loop.", ],
			["Cannot use \"continue\" outside of a loop.", ],
			["Cannot use \"self\" inside a static function.", ],
			["Cannot use implicit \"super\" call outside of a function.", ],
			["Cannot use `super()` inside a lambda.", ],
		],
		"raw": [
			"'self' not present in static function.",
			"Cannot use \"break\" outside of a loop.",
			"Cannot use \"continue\" outside of a loop.",
			"Cannot use \"self\" inside a static function.",
			"Cannot use implicit \"super\" call outside of a function.",
			"Cannot use `super()` inside a lambda.",
		],
		"code": ErrorCode.MISPLACED_KEYWORD,
	},
	{
		"patterns": [
			["Cannot call something that isn't a function.", ],
			["Compiler bug (please report): incorrect callee type in call node.", ],
			["Analyzer bug: Wrong \"range()\" argument count.)", ],
			["Signal parameters cannot have a default value.", ],
			["Cannot have parameters after the rest parameter.", ],
			["The rest parameter cannot have a default value.", ],
			["Cannot have mandatory parameters after optional parameters.", ],
			["Static constructor cannot have parameters.", ],
			["Cannot use a variable bind with multiple patterns.", ],
			["Nested typed collections are not supported.", ],
			["Annotation \"", "\" requires at most ", " arguments, but ", " were given.", ],
			["Annotation \"", "\" requires at least ", " arguments, but ", " were given.", ],
			["Argument ", " of annotation \"", "\" must be a string literal.\", i + 1, p_annotation->name), argument)", ],
			["\"@icon\" annotation argument must contain the path to the icon.", ],
			["Argument ", " of annotation \"", "\" is empty.", ],
			["Argument ", " of annotation \"", "\" contains a comma. Use separate arguments instead.", ],
			["Invalid argument ", " of annotation \"@export_flags\": Expected flag name.", ],
			["Invalid argument ", " of annotation \"@export_flags\": Expected flag value.", ],
			["Invalid argument ", " of annotation \"@export_flags\": The flag value must be a valid integer.", ],
			["Invalid argument ", " of annotation \"@export_flags\": The flag value must be at least 1 and at most 2 ** ", " - 1.", ],
			["Invalid argument ", " of annotation \"@export_flags\": Starting from argument ", ", the flag value must be specified explicitly.", ],
			["Invalid argument ", " of annotation \"@export_node_path\": The class \"", "\" was not found in the global scope.", ],
			["Invalid argument ", " of annotation \"@export_node_path\": The class \"", "\" does not inherit \"Node\".", ],
			["Invalid RPC argument. Must be one of: \"call_local\"/\"call_remote\" (local calls), \"any_peer\"/\"authority\" (permission), \"reliable\"/\"unreliable\"/\"unreliable_ordered\" (transfer mode).", ],
			["Invalid RPC config. The locality (\"call_local\"/\"call_remote\") must be specified no more than once.", ],
			["Invalid RPC config. The permission (\"any_peer\"/\"authority\") must be specified no more than once.", ],
			["Invalid RPC config. The transfer mode (\"reliable\"/\"unreliable\"/\"unreliable_ordered\") must be specified no more than once.", ],
			["Typed arrays require exactly one collection element type.", ],
			["Typed dictionaries require exactly two collection element types.", ],
			["Invalid argument for annotation \"", "\": argument ", " should be \"", "\" but is \"", "\".", ],
			["Typed arrays are currently not supported for the rest parameter.", ],
			["Invalid call for \"range()\" function. Expected at least 1 argument, none given.", ],
			["Invalid call for \"range()\" function. Expected at most 3 arguments, ", " given.", ],
			["Invalid constructor \"Object(\", use \"Object.new()\"  instead.)", ],
			["Invalid argument for \"", "()\"  constructor: argument ", " should be \"", "\" but is \"", "\".) ", ],
			["Invalid argument for \"", "()\"  function: ", ],
			["Invalid call for function \"", "\".", ],
			["Too many arguments for \"", "()\"  call. Expected at most ", " but received ", ".", ],
			["Too few arguments for \"", "()\"  call. Expected at least ", " but received ", ".", ],
			["Cannot construct native class \"", "\" because it is an engine singleton.", ],
			["Cannot construct abstract class \"", "\".", ],
			["Failed to construct \"", "\".", ],
			["Too few arguments for \"", "()\"  call. Expected at least ", " but received ", ".", ],
			["Too many arguments for \"", "()\"  call. Expected at most ", " but received ", ".", ],
			["Invalid argument for \"", "()\"  function: argument ", " should be \"", "\" but is \"", "\".", ],
		],
		"raw": [
			"Cannot call something that isn't a function.",
			"Compiler bug (please report): incorrect callee type in call node.",
			"Analyzer bug: Wrong \"range()\" argument count.)",
			"Signal parameters cannot have a default value.",
			"Cannot have parameters after the rest parameter.",
			"The rest parameter cannot have a default value.",
			"Cannot have mandatory parameters after optional parameters.",
			"Static constructor cannot have parameters.",
			"Cannot use a variable bind with multiple patterns.",
			"Nested typed collections are not supported.",
			"Annotation \"%NAME%\" requires at most %EXPECTED_SIZE% arguments, but %SIZE% were given.",
			"Annotation \"%NAME%\" requires at least %EXPECTED_SIZE% arguments, but %SIZE% were given.",
			"Argument %ARG_IDX% of annotation \"%IDENTIFIER%\" must be a string literal.",
			"\"@icon\" annotation argument must contain the path to the icon.",
			"Argument %ARG_IDX% of annotation \"%IDENTIFIER%\" is empty.",
			"Argument %ARG_IDX% of annotation \"%IDENTIFIER%\" contains a comma. Use separate arguments instead.",
			"Invalid argument %ARG_IDX% of annotation \"@export_flags\": Expected flag name.",
			"Invalid argument %ARG_IDX% of annotation \"@export_flags\": Expected flag value.",
			"Invalid argument %ARG_IDX% of annotation \"@export_flags\": The flag value must be a valid integer.",
			"Invalid argument %ARG_IDX% of annotation \"@export_flags\": The flag value must be at least 1 and at most 2 ** %ARG_COUNT% - 1.",
			"Invalid argument %ARG_IDX% of annotation \"@export_flags\": Starting from argument %FLAG_IDX%, the flag value must be specified explicitly.",
			"Invalid argument %ARG_IDX% of annotation \"@export_node_path\": The class \"%IDENTIFIER%\" was not found in the global scope.",
			"Invalid argument %ARG_IDX% of annotation \"@export_node_path\": The class \"%IDENTIFIER%\" does not inherit \"Node\".",
			"Invalid RPC argument. Must be one of: \"call_local\"/\"call_remote\" (local calls), \"any_peer\"/\"authority\" (permission), \"reliable\"/\"unreliable\"/\"unreliable_ordered\" (transfer mode).",
			"Invalid RPC config. The locality (\"call_local\"/\"call_remote\") must be specified no more than once.",
			"Invalid RPC config. The permission (\"any_peer\"/\"authority\") must be specified no more than once.",
			"Invalid RPC config. The transfer mode (\"reliable\"/\"unreliable\"/\"unreliable_ordered\") must be specified no more than once.",
			"Typed arrays require exactly one collection element type.",
			"Typed dictionaries require exactly two collection element types.",
			"Invalid argument for annotation \"%IDENTIFIER%\": argument %IDX% should be \"%TYPE%\" but is \"%OTHER_TYPE%\".",
			"Typed arrays are currently not supported for the rest parameter.",
			"Invalid call for \"range()\" function. Expected at least 1 argument, none given.",
			"Invalid call for \"range()\" function. Expected at most 3 arguments, %SIZE% given.",
			"Invalid constructor \"Object(\", use \"Object.new()\"  instead.)",
			"Invalid argument for \"%TYPE%()\"  constructor: argument %ARG_IDX% should be \"%TYPE%\" but is \"%OTHER_TYPE%\".) ",
			"Invalid argument for \"%FUNCTION_NAME%()\"  function: %VALUE%",
			"Invalid call for function \"%FUNCTION_NAME%\".",
			"Too many arguments for \"%FUNCTION_NAME%()\"  call. Expected at most %EXPECTED% but received %SIZE%.",
			"Too few arguments for \"%FUNCTION_NAME%()\"  call. Expected at least %EXPECTED% but received %SIZE%.",
			"Cannot construct native class \"%NATIVE_TYPE%\" because it is an engine singleton.",
			"Cannot construct abstract class \"%CLASS%\".",
			"Failed to construct \"%TYPE%\".",
			"Too few arguments for \"%FUNCTION_NAME%()\"  call. Expected at least %COUNT% but received %SIZE%.",
			"Too many arguments for \"%FUNCTION_NAME%()\"  call. Expected at most %COUNT% but received %SIZE%.",
			"Invalid argument for \"%FUNCTION_NAME%()\"  function: argument %IDX% should be \"%TYPE%\" but is \"%OTHER_TYPE%\".",
		],
		"code": ErrorCode.INVALID_ARGUMENTS,
	},
	{
		"patterns": [
			["Must use '", "' instead of 'self.", "' in getter.", ],
			["Must use '", "' instead of 'self.", "' in setter.", ],
			["Unexpected standalone annotation.", ],
			["Annotation \"", "\" cannot be applied to a ", ".", ],
			["Annotation \"", "\" must be at the top of the script, before \"extends\" and \"class_name\".", ],
			["Annotation \"", "\" is not allowed in this level.", ],
			["Annotation \"", "\" does not precede a valid target, so it will have no effect.", ],
			["Annotation \"", "\" cannot be applied to a statement.", ],
			["Annotation \"", "\" is not allowed in this level.", ],
			["Rest pattern can only be used inside array and dictionary patterns.", ],
			["The \"..\" pattern must be the last element in the pattern array.", ],
			["The \"..\" pattern must be the last element in the pattern dictionary.", ],
			["The \"..\" pattern cannot be used as a value.", ],
			["\"@abstract\" annotation cannot be applied to static functions.", ],
			["\"@onready\" can only be used in classes that inherit \"Node\".", ],
			["\"@onready\" annotation cannot be applied to a static variable.", ],
			["Annotation \"", "\" cannot be applied to a static variable.", ],
			["Tool buttons can only be used in tool scripts (add \"@tool\" to the top of the script).", ],
			["Warning \"", "\" is not being ignored by \"@warning_ignore_start\".", ],
			["Global enum \"", "\" cannot be used on its own.", ],
		],
		"raw": [
			"Must use '%IDENTIFIER%' instead of 'self.%IDENTIFIER%' in getter.",
			"Must use '%IDENTIFIER%' instead of 'self.%IDENTIFIER%' in setter.",
			"Unexpected standalone annotation.",
			"Annotation \"%NAME%\" cannot be applied to a %MEMBER_KIND%.",
			"Annotation \"%NAME%\" must be at the top of the script, before \"extends\" and \"class_name\".",
			"Annotation \"%NAME%\" is not allowed in this level.",
			"Annotation \"%IDENTIFIER%\" does not precede a valid target, so it will have no effect.",
			"Annotation \"%NAME%\" cannot be applied to a statement.",
			"Annotation \"%IDENTIFIER%\" is not allowed in this level.",
			"Rest pattern can only be used inside array and dictionary patterns.",
			"The \"..\" pattern must be the last element in the pattern array.",
			"The \"..\" pattern must be the last element in the pattern dictionary.",
			"The \"..\" pattern cannot be used as a value.",
			"\"@abstract\" annotation cannot be applied to static functions.",
			"\"@onready\" can only be used in classes that inherit \"Node\".",
			"\"@onready\" annotation cannot be applied to a static variable.",
			"Annotation \"%IDENTIFIER%\" cannot be applied to a static variable.",
			"Tool buttons can only be used in tool scripts (add \"@tool\" to the top of the script).",
			"Warning \"%WARNING%\" is not being ignored by \"@warning_ignore_start\".",
			"Global enum \"%NAME%\" cannot be used on its own.",
		],
		"code": ErrorCode.MISPLACED_IDENTIFIER,
	},
	{
		"patterns": [
			["Compiler bug (please report): Expected the assignee to be an identifier here.", ],
			["Assignment is not allowed inside an expression.", ],
			["Only identifier, attribute access, and subscription access can be used as assignment target.", ],
		],
		"raw": [
			"Compiler bug (please report): Expected the assignee to be an identifier here.",
			"Assignment is not allowed inside an expression.",
			"Only identifier, attribute access, and subscription access can be used as assignment target.",
		],
		"code": ErrorCode.ASSIGNING_TO_EXPRESSION,
	},
	{
		"patterns": [
			["Compiler bug (please report): Unexpected node in parse tree while parsing expression.", ],
			["Compiler bug (please report): unexpected node in parse tree while parsing statement.", ],
			["Too many statement errors.", ],
			["Standalone lambdas cannot be accessed. Consider assigning it to a variable.", ],
		],
		"raw": [
			"Compiler bug (please report): Unexpected node in parse tree while parsing expression.",
			"Compiler bug (please report): unexpected node in parse tree while parsing statement.",
			"Too many statement errors.",
			"Standalone lambdas cannot be accessed. Consider assigning it to a variable.",
		],
		"code": ErrorCode.STANDALONE_EXPRESSION,
	},
	{
		"patterns": [
			["Compiler bug (please report): Reaching the end of pattern compilation without matching a pattern.", ],
			["Expected end of statement after ", ", found \"", "\" instead.", ],
			["Expected newline after a standalone annotation.", ],
			["Expected newline after comment string.", ],
			["Expected end of file.", ],
			["Expected expression for variable initial value after \"=\".", ],
			["Inline setter/getter setting cannot span across multiple lines (use \"\\\" if needed).", ],
			["Expected signal parameter name.", ],
			["Expected expression value after \"=\".", ],
			["Expected expression as the annotation argument.", ],
			["Expected expression to assert.", ],
			["Expected error message for assert after \",\".", ],
			["Expected conditional expression after \"", "\".", ],
			["Expected expression to test after \"match\".", ],
			["No pattern found for \"match\" branch.", ],
			["Expected expression for pattern guard after \"when\".", ],
			["Expected expression as key for dictionary pattern.", ],
			["Expected expression for match pattern.", ],
			["Expected conditional expression after \"while\".", ],
			["Expected expression after \"-\" operator.", ],
			["Expected expression after \"+\" operator.", ],
			["Expected expression after \"~\" operator.", ],
			["Expected expression after \"not\" operator.", ],
			["Expected expression after \"!\" operator.", ],
			["Expected expression after \"", "\" operator.", ],
			["Expected expression as ternary condition after \"if\".", ],
			["Expected expression after \"else\".", ],
			["Expected an expression after \"=\".", ],
			["Expected signal or coroutine after \"await\".", ],
			["Expected expression as array element.", ],
			["Expected expression as dictionary key.", ],
			["Expected \":\" or \"=\" after dictionary key.", ],
			["Expected expression as dictionary value.", ],
			["Expected grouping expression.", ],
			["Expected expression after \"[\".", ],
			["Expected expression as the function argument.", ],
			["Expected node path as string or identifier after \"", "\".", ],
			["Expected node path as string or identifier after \"", "\".", ],
			["Expected resource path after \"(\".", ],
			["Expected type for collection after \"", "\".\""],
			["Expected superclass name after \"extends\".", ],
			["Expected superclass name after \".\".", ],
			["Expected variable name after \"var\".", ],
			["Expected \"(\" after \"set\".", ],
			["Expected parameter name after \"(\".", ],
			["Expected \")\"  after parameter name.", ],
			["Expected \":\" after \")\".", ],
			["Expected \"=\" after \"set\"", ],
			["Expected setter function name after \"=\".", ],
			["Expected \")\"  after \"get(\".", ],
			["Expected \":\" after \"get()\".", ],
			["Expected \":\" or \"(\" after \"get\".", ],
			["Expected \"=\" after \"get\"", ],
			["Expected getter function name after \"=\".", ],
			["Expected constant name after \"const\".", ],
			["Expected initializer after constant name.", ],
			["Expected parameter name.", ],
			["Expected signal name after \"signal\".", ],
			["Expected closing \")\"  after signal parameters.", ],
			["Expected \"{\" after enum.", ],
			["Expected \"{\" after enum name.", ],
			["Expected identifier for enum key.", ],
			["Expected closing \"}\"  for enum.", ],
			["Expected closing \")\"  after ", " parameters.", ],
			["Expected \":\" after lambda declaration.", ],
			["Expected function name after \"func\".", ],
			["Expected opening \"(\" after function name.", ],
			["Expected \")\"  after annotation arguments.", ],
			["Expected newline after \";\" at the end of ", ".", ],
			["Expected \"(\" after \"assert\".", ],
			["Expected \")\"  after assert expression.", ],
			["Expected loop variable name after \"for\".", ],
			["Expected \":\" after \"for\" condition.", ],
			["Expected \":\" after \"", "\" condition.", ],
			["Expected \":\" after \"else\".", ],
			["Expected \":\" after \"match\" expression.", ],
			["Expected a newline after \"match\" statement.", ],
			["Expected newline after \"pass\".", ],
			["Expected \":\" after \"match\" patterns.", ],
			["Expected \":\" or \"when\" after \"match\" pattern guard.", ],
			["Expected bind name after \"var\".", ],
			["Expected \"]\" to close the array pattern.", ],
			["Expected \"}\"  to close the dictionary pattern.", ],
			["Expected \":\" after \"while\" condition.", ],
			["Expected closing \"]\" after array elements.", ],
			["Expected closing \"}\"  after dictionary elements.", ],
			["Expected closing \")\"  after grouping expression.", ],
			["Expected identifier after \".\"  for attribute access.", ],
			["Expected \"]\" after subscription index.", ],
			["Expected \".\"  or \"(\" after \"super\".", ],
			["Expected function name after \".\".", ],
			["Expected \"(\" after function name.", ],
			["Expected closing \")\"  after call arguments.", ],
			["Expected \"(\" after \"preload\".", ],
			["Expected \")\"  after preload path.", ],
			["Expected opening \"(\" after lambda name.", ],
			["Expected opening \"(\" after \"func\".", ],
			["Expected closing \"]\" after collection type.", ],
			["Expected inner type name after \".\".", ],
			["A lambda function must have a \":\" followed by a body.", ],
			["A function must either have a \":\" followed by a body, or be marked as \"@abstract\".", ],
			["Expected exponent value after \"e\".", ],
			["Expected ", " digit after \"0", "\".", ],
			["Unterminated string.", ],
			["Unterminated string.", ],
			["Expected new line after \""],
			["Expected annotation identifier after \"@\".", ],
		],
		"raw": [
			"Compiler bug (please report): Reaching the end of pattern compilation without matching a pattern.",
			"Expected end of statement after %CONTEXT%, found \"%NAME%\" instead.",
			"Expected newline after a standalone annotation.",
			"Expected newline after comment string.",
			"Expected end of file.",
			"Expected expression for variable initial value after \"=\".",
			"Inline setter/getter setting cannot span across multiple lines (use \"\\\" if needed).",
			"Expected signal parameter name.",
			"Expected expression value after \"=\".",
			"Expected expression as the annotation argument.",
			"Expected expression to assert.",
			"Expected error message for assert after \",\".",
			"Expected conditional expression after \"%TOKEN%\".",
			"Expected expression to test after \"match\".",
			"No pattern found for \"match\" branch.",
			"Expected expression for pattern guard after \"when\".",
			"Expected expression as key for dictionary pattern.",
			"Expected expression for match pattern.",
			"Expected conditional expression after \"while\".",
			"Expected expression after \"-\" operator.",
			"Expected expression after \"+\" operator.",
			"Expected expression after \"~\" operator.",
			"Expected expression after \"not\" operator.",
			"Expected expression after \"!\" operator.",
			"Expected expression after \"%NAME%\" operator.",
			"Expected expression as ternary condition after \"if\".",
			"Expected expression after \"else\".",
			"Expected an expression after \"=\".",
			"Expected signal or coroutine after \"await\".",
			"Expected expression as array element.",
			"Expected expression as dictionary key.",
			"Expected \":\" or \"=\" after dictionary key.",
			"Expected expression as dictionary value.",
			"Expected grouping expression.",
			"Expected expression after \"[\".",
			"Expected expression as the function argument.",
			"Expected node path as string or identifier after \"%NAME%\".",
			"Expected node path as string or identifier after \"%PREVIOUS_TOKEN%\".",
			"Expected resource path after \"(\".",
			"Expected type for collection after \"%\"%\".\"",
			"Expected superclass name after \"extends\".",
			"Expected superclass name after \".\".",
			"Expected variable name after \"var\".",
			"Expected \"(\" after \"set\".",
			"Expected parameter name after \"(\".",
			"Expected \")\"  after parameter name.",
			"Expected \":\" after \")\".",
			"Expected \"=\" after \"set\"",
			"Expected setter function name after \"=\".",
			"Expected \")\"  after \"get(\".",
			"Expected \":\" after \"get()\".",
			"Expected \":\" or \"(\" after \"get\".",
			"Expected \"=\" after \"get\"",
			"Expected getter function name after \"=\".",
			"Expected constant name after \"const\".",
			"Expected initializer after constant name.",
			"Expected parameter name.",
			"Expected signal name after \"signal\".",
			"Expected closing \")\"  after signal parameters.",
			"Expected \"{\" after enum.",
			"Expected \"{\" after enum name.",
			"Expected identifier for enum key.",
			"Expected closing \"}\"  for enum.",
			"Expected closing \")\"  after %TYPE% parameters.",
			"Expected \":\" after lambda declaration.",
			"Expected function name after \"func\".",
			"Expected opening \"(\" after function name.",
			"Expected \")\"  after annotation arguments.",
			"Expected newline after \";\" at the end of %CONTEXT%.",
			"Expected \"(\" after \"assert\".",
			"Expected \")\"  after assert expression.",
			"Expected loop variable name after \"for\".",
			"Expected \":\" after \"for\" condition.",
			"Expected \":\" after \"%TOKEN%\" condition.",
			"Expected \":\" after \"else\".",
			"Expected \":\" after \"match\" expression.",
			"Expected a newline after \"match\" statement.",
			"Expected newline after \"pass\".",
			"Expected \":\" after \"match\" patterns.",
			"Expected \":\" or \"when\" after \"match\" pattern guard.",
			"Expected bind name after \"var\".",
			"Expected \"]\" to close the array pattern.",
			"Expected \"}\"  to close the dictionary pattern.",
			"Expected \":\" after \"while\" condition.",
			"Expected closing \"]\" after array elements.",
			"Expected closing \"}\"  after dictionary elements.",
			"Expected closing \")\"  after grouping expression.",
			"Expected identifier after \".\"  for attribute access.",
			"Expected \"]\" after subscription index.",
			"Expected \".\"  or \"(\" after \"super\".",
			"Expected function name after \".\".",
			"Expected \"(\" after function name.",
			"Expected closing \")\"  after call arguments.",
			"Expected \"(\" after \"preload\".",
			"Expected \")\"  after preload path.",
			"Expected opening \"(\" after lambda name.",
			"Expected opening \"(\" after \"func\".",
			"Expected closing \"]\" after collection type.",
			"Expected inner type name after \".\".",
			"A lambda function must have a \":\" followed by a body.",
			"A function must either have a \":\" followed by a body, or be marked as \"@abstract\".",
			"Expected exponent value after \"e\".",
			"Expected %DIGIT% digit after \"0%TOKEN%\".",
			"Unterminated string.",
			"Unterminated string.",
			"Expected new line after \"\".",
			"Expected annotation identifier after \"@\".",
		],
		"code": ErrorCode.UNEXPECTED_EOL,
	},
	{
		"patterns": [
			["Local constant must have a constant value as initializer.", ],
			["Expected initializer expression for constant.", ],
			["Local constant \"", "\" is not resolved at this point.", ],
			["Enum values must be constant.", ],
			["Argument ", " of annotation \"", "\" isn't a constant expression.", ],
			["Assigned value for ", " \"", "\" isn't a constant expression.", ],
			["Expression in match pattern must be a constant expression, an identifier, or an attribute access (\"A.B\").", ],
			["Expression in dictionary pattern key must be a constant.", ],
			["Preloaded path must be a constant string.", ],
		],
		"raw": [
			"Local constant must have a constant value as initializer.",
			"Expected initializer expression for constant.",
			"Local constant \"%IDENTIFIER%\" is not resolved at this point.",
			"Enum values must be constant.",
			"Argument %IDX% of annotation \"%NAME%\" isn't a constant expression.",
			"Assigned value for %KIND% \"%NAME%\" isn't a constant expression.",
			"Expression in match pattern must be a constant expression, an identifier, or an attribute access (\"A.B\").",
			"Expression in dictionary pattern key must be a constant.",
			"Preloaded path must be a constant string.",
		],
		"code": ErrorCode.EXPECTED_CONSTANT_EXPRESSION,
	},
	{
		"patterns": [
			["The class \"", "\" shadows a native class", ],
			["The member \"", "\" shadows a native class.", ],
			["The member \"", "\" cannot have the same name as a builtin type.", ],
			["Class \"", "\" hides a built-in type.", ],
			["Class \"", "\" hides a native class.", ],
			["Class \"", "\" hides a global script class.", ],
			["Class \"", "\" hides an autoload singleton.", ],
		],
		"raw": [
			"The class \"%IDENTIFIER%\" shadows a native class",
			"The member \"%MEMBER_NAME%\" shadows a native class.",
			"The member \"%MEMBER_NAME%\" cannot have the same name as a builtin type.",
			"Class \"%CLASS_NAME%\" hides a built-in type.",
			"Class \"%CLASS_NAME%\" hides a native class.",
			"Class \"%CLASS_NAME%\" hides a global script class.",
			"Class \"%CLASS_NAME%\" hides an autoload singleton.",
		],
		"code": ErrorCode.SHADOWED_VARIABLE,
	},
	{
		"patterns": [
			["Parser bug (please report): Empty native type in base class \"", "\"", ],
			["Compiler bug (please report): script native type is null.", ],
			["Compiler bug (please report): base script type is null.", ],
			["Could not parse base class \"", "\" from \"", "\": ", ],
			["Could not populate class members of base class \"", "\" in \"", "\".", ],
			["Parser bug (please report): invalid inheritance.", ],
			["Expected identifier for the class name after \"class\".", ],
			["Expected \":\" after class declaration.", ],
			["Expected identifier for the global class name after \"class_name\".", ],
			["Could not resolve super class inheritance from \"", "\".", ],
			["Could not resolve an empty super class path.", ],
			["Could not resolve super class inheritance from \"", "\".", ],
			["Cannot inherit native class \"", "\" because it is an engine singleton.", ],
			["Could not resolve inheritance for class \"", "\".", ],
			["Enums cannot contain nested types.", ],
			["Class \"", "\" is not abstract but contains abstract methods. Mark the class as \"@abstract\" or remove \"@abstract\" from all methods in this class.", ],
			["Constructor cannot have an explicit return type.", ],
			["Static constructor cannot have an explicit return type.", ],
			["An abstract function cannot have a body.", ],
			["Class \"", "\" cannot be constructed as it is based on abstract native class \"", "\".", ],
			["Script \"", "\" cannot be constructed as it is based on abstract native class \"", "\".", ],
			["Native class \"", "\" cannot be constructed as it is abstract.", ],
		],
		"raw": [
			"Parser bug (please report): Empty native type in base class \"%PATH%\"",
			"Compiler bug (please report): script native type is null.",
			"Compiler bug (please report): base script type is null.",
			"Could not parse base class \"%IDENTIFIER%\" from \"%PATH%\": %ERROR_NAME%",
			"Could not populate class members of base class \"%IDENTIFIER%\" in \"%PATH%\".",
			"Parser bug (please report): invalid inheritance.",
			"Expected identifier for the class name after \"class\".",
			"Expected \":\" after class declaration.",
			"Expected identifier for the global class name after \"class_name\".",
			"Could not resolve super class inheritance from \"%EXTENDS_PATH%\".",
			"Could not resolve an empty super class path.",
			"Could not resolve super class inheritance from \"%NAME%\".",
			"Cannot inherit native class \"%NAME%\" because it is an engine singleton.",
			"Could not resolve inheritance for class \"%NAME%\".",
			"Enums cannot contain nested types.",
			"Class \"%CLASS_NAME%\" is not abstract but contains abstract methods. Mark the class as \"@abstract\" or remove \"@abstract\" from all methods in this class.",
			"Constructor cannot have an explicit return type.",
			"Static constructor cannot have an explicit return type.",
			"An abstract function cannot have a body.",
			"Class \"%TYPE%\" cannot be constructed as it is based on abstract native class \"%OTHER_CLASS%\".",
			"Script \"%TYPE%\" cannot be constructed as it is based on abstract native class \"%OTHER_CLASS%\".",
			"Native class \"%BASE_NATIVE%\" cannot be constructed as it is abstract.",
		],
		"code": ErrorCode.INVALID_CLASS_DECLARATION,
	},
	{
		"patterns": [
			["\"class_name\" can only be used once.", ],
			["\"extends\" can only be used once.", ],
			["Cannot use \"extends\" more than once in the same class.", ],
			[" \"", "\" has the same name as a previously declared ", ".", ],
			["Properties can only have one setter.", ],
			["Properties can only have one getter.", ],
			["Name \"", "\" was already in this enum (at line ", ").", ],
			["Name \"", "\" is already used as a class ", ".", ],
			["Parameter with name \"", "\" was already declared for this ", ".", ],
			["There is already a ", " named \"", "\" declared in this scope.", ],
			["There is already a ", " named \"", "\" declared in this scope.", ],
			["There is already a ", " named \"", "\" declared in this scope.", ],
			["Bind variable name \"", "\" was already used in this pattern.", ],
			["There's already a ", " named \"", "\" in this scope.", ],
			["\"@tool\" annotation can only be used once.", ],
			["\"@icon\" annotation can only be used once.", ],
			["\"", "\" annotation can only be used once per script.", ],
			["\"@abstract\" annotation can only be used once per class.", ],
			["\"@abstract\" annotation can only be used once per function.", ],
			["\"@onready\" annotation can only be used once per variable.", ],
			["Annotation \"", "\" cannot be used with another \"@export\" annotation.", ],
			["Warning \"", "\" is already being ignored by \"@warning_ignore_start\" at line ", ".", ],
			["RPC annotations can only be used once per function.", ],
			["Member \"", "\" redefined (original in native class '", "')", ],
			["The member \"", "\" already exists in parent class ", ".", ],
			["Key \"", "\" was already used in this dictionary (at line ", ").", ],
		],
		"raw": [
			"\"class_name\" can only be used once.",
			"\"extends\" can only be used once.",
			"Cannot use \"extends\" more than once in the same class.",
			"%KIND% \"%IDENTIFIER%\" has the same name as a previously declared %TYPE%.",
			"Properties can only have one setter.",
			"Properties can only have one getter.",
			"Name \"%IDENTIFIER%\" was already in this enum (at line %LINE%).",
			"Name \"%IDENTIFIER%\" is already used as a class %TYPE_NAME%.",
			"Parameter with name \"%NAME%\" was already declared for this %TYPE%.",
			"There is already a %LOCAL_IDENTIFIER% named \"%IDENTIFIER%\" declared in this scope.",
			"There is already a %IDENTIFIER% named \"%CONSTANT_IDENTIFIER%\" declared in this scope.",
			"There is already a %LOCAL_IDENTIFIER% named \"%FOR_IDENTIFIER%\" declared in this scope.",
			"Bind variable name \"%NAME%\" was already used in this pattern.",
			"There's already a %NAME% named \"%NAME%\" in this scope.",
			"\"@tool\" annotation can only be used once.",
			"\"@icon\" annotation can only be used once.",
			"\"%IDENTIFIER%\" annotation can only be used once per script.",
			"\"@abstract\" annotation can only be used once per class.",
			"\"@abstract\" annotation can only be used once per function.",
			"\"@onready\" annotation can only be used once per variable.",
			"Annotation \"%IDENTIFIER%\" cannot be used with another \"@export\" annotation.",
			"Warning \"%WARNING%\" is already being ignored by \"@warning_ignore_start\" at line %LINE%.",
			"RPC annotations can only be used once per function.",
			"Member \"%MEMBER_NAME%\" redefined (original in native class '%NATIVE_TYPE%')",
			"The member \"%MEMBER_NAME%\" already exists in parent class %PARENT_CLASS%.",
			"Key \"%KEY%\" was already used in this dictionary (at line %LINE%).",
		],
		"code": ErrorCode.DUPLICATE_DECLARATION,
	},
	{
		"patterns": [
			["Only strings or identifiers can be used after \"extends\", found \"", "\" instead.", ],
			["Expected type after \":\"", ],
			["Expected return type or \"void\" after \"->\".", ],
			["Expected type specifier after \":\".", ],
			["Expected type specifier after \"as\".", ],
			["Expected type specifier after \"is\".", ],
			["Expected type specifier after \"is not\".", ],
			["\"void\" is only allowed for a function return type.", ],
			["Cannot use ", " \"", "\" in extends chain.", ],
			["Local ", "IDENTIFIER\" cannot be used as a type.", ],
			["Builtin type cannot be used as a name on its own.", ],
			["Type \"", "\" in base \"", "\" cannot be used on its own.", ],
		],
		"raw": [
			"Only strings or identifiers can be used after \"extends\", found \"%TYPE%\" instead.",
			"Expected type after \":\"",
			"Expected return type or \"void\" after \"->\".",
			"Expected type specifier after \":\".",
			"Expected type specifier after \"as\".",
			"Expected type specifier after \"is\".",
			"Expected type specifier after \"is not\".",
			"\"void\" is only allowed for a function return type.",
			"Cannot use %TYPE% \"%IDENTIFIER%\" in extends chain.",
			"Local %TYPE \"%IDENTIFIER\" cannot be used as a type.",
			"Builtin type cannot be used as a name on its own.",
			"Type \"%NAME%\" in base \"%BASE%\" cannot be used on its own.",
		],
		"code": ErrorCode.MISPLACED_TYPE_IDENTIFIER,
	},
	{
		"patterns": [
			["Expected \"func\" or \"var\" after \"static\".", ],
			["Expected \"get\" or \"set\" for property declaration.", ],
			["\"@deprecated\" annotation does not exist. Use \"## @deprecated: Reason here.\" instead.", ],
			["\"@experimental\" annotation does not exist. Use \"## @experimental: Reason here.\" instead.", ],
			["\"@tutorial\" annotation does not exist. Use \"## @tutorial(Title): https://example.com\" instead.", ],
			["Expected identifier or string as Lua-style dictionary key (e.g \"{ key = value }\").", ],
			["Expected \"", "\" after dictionary key. Mixing dictionary styles is not allowed.", ],
			["\"%\" is only valid in the beginning of a node name (either after \"$\" or after \"/\")", ],
			["\"/\" is only valid at the beginning of the path or after a node name.", ],
			["Unexpected underscore after \"0", "\".", ],
			["Unexpected underscore after decimal point.", ],
			["Identifier \"", "\" is visually similar to the GDScript keyword \"", "\" and thus not allowed.", ],
		],
		"raw": [
			"Expected \"func\" or \"var\" after \"static\".",
			"Expected \"get\" or \"set\" for property declaration.",
			"\"@deprecated\" annotation does not exist. Use \"## @deprecated: Reason here.\" instead.",
			"\"@experimental\" annotation does not exist. Use \"## @experimental: Reason here.\" instead.",
			"\"@tutorial\" annotation does not exist. Use \"## @tutorial(Title): https://example.com\" instead.",
			"Expected identifier or string as Lua-style dictionary key (e.g \"{ key = value }\").",
			"Expected \"%TOKEN%\" after dictionary key. Mixing dictionary styles is not allowed.",
			"\"%\" is only valid in the beginning of a node name (either after \"$\" or after \"/\")",
			"\"/\" is only valid at the beginning of the path or after a node name.",
			"Unexpected underscore after \"0%TOKEN%\".",
			"Unexpected underscore after decimal point.",
			"Identifier \"%IDENTIFIER%\" is visually similar to the GDScript keyword \"%KEYWORD%\" and thus not allowed.",
		],
		"code": ErrorCode.UNEXPECTED_CHARACTER_IN_KEYWORD,
	},
	{
		"patterns": [
			["The \"export\" keyword was removed in Godot 4. Use an export annotation (\"@export\", \"@export_range\", etc.) instead.", ],
			["The \"tool\" keyword was removed in Godot 4. Use the \"@tool\" annotation instead.", ],
			["The \"onready\" keyword was removed in Godot 4. Use the \"@onready\" annotation instead.", ],
			["The \"remote\" keyword was removed in Godot 4. Use the \"@rpc\" annotation with \"any_peer\" instead.", ],
			["The \"remotesync\" keyword was removed in Godot 4. Use the \"@rpc\" annotation with \"any_peer\" and \"call_local\" instead.", ],
			["The \"puppet\" keyword was removed in Godot 4. Use the \"@rpc\" annotation with \"authority\" instead.", ],
			["The \"puppetsync\" keyword was removed in Godot 4. Use the \"@rpc\" annotation with \"authority\" and \"call_local\" instead.", ],
			["The \"master\" keyword was removed in Godot 4. Use the \"@rpc\" annotation with \"any_peer\" and perform a check inside the function instead.", ],
			["The \"mastersync\" keyword was removed in Godot 4. Use the \"@rpc\" annotation with \"any_peer\" and \"call_local\", and perform a check inside the function instead.", ],
			["\"yield\" was removed in Godot 4. Use \"await\" instead.", ],
		],
		"raw": [
			"The \"export\" keyword was removed in Godot 4. Use an export annotation (\"@export\", \"@export_range\", etc.) instead.",
			"The \"tool\" keyword was removed in Godot 4. Use the \"@tool\" annotation instead.",
			"The \"onready\" keyword was removed in Godot 4. Use the \"@onready\" annotation instead.",
			"The \"remote\" keyword was removed in Godot 4. Use the \"@rpc\" annotation with \"any_peer\" instead.",
			"The \"remotesync\" keyword was removed in Godot 4. Use the \"@rpc\" annotation with \"any_peer\" and \"call_local\" instead.",
			"The \"puppet\" keyword was removed in Godot 4. Use the \"@rpc\" annotation with \"authority\" instead.",
			"The \"puppetsync\" keyword was removed in Godot 4. Use the \"@rpc\" annotation with \"authority\" and \"call_local\" instead.",
			"The \"master\" keyword was removed in Godot 4. Use the \"@rpc\" annotation with \"any_peer\" and perform a check inside the function instead.",
			"The \"mastersync\" keyword was removed in Godot 4. Use the \"@rpc\" annotation with \"any_peer\" and \"call_local\", and perform a check inside the function instead.",
			"\"yield\" was removed in Godot 4. Use \"await\" instead.",
		],
		"code": ErrorCode.DEPRECATED_KEYWORD,
	},
	{
		"patterns": [
			["Unexpected ", " in class body.", ],
			["Expected statement, found \"", "\" instead.", ],
			["Parser bug: parsing literal node without literal token.", ],
			["Unexpected \"", "\" in node path.", ],
			["Unexpected \"?\" in source. If you want a ternary operator, use \"truthy_value if true_condition else falsy_value\".", ],
			["Closing \"", "\" doesn't have an opening counterpart.", ],
			["Closing \"", "\" doesn't match the opening \"", "\".", ],
			["Multiple underscores cannot be adjacent in a numeric literal.", ],
			["Cannot use a decimal point twice in a number.", ],
			["Cannot use a decimal point in a hexadecimal number.", ],
			["Cannot use a decimal point in a binary number.", ],
			["Multiple underscores cannot be adjacent in a numeric literal.", ],
			["Multiple underscores cannot be adjacent in a numeric literal.", ],
			["Cannot use a decimal point twice in a number.", ],
			["Invalid hexadecimal digit in unicode escape sequence.", ],
			["Invalid escape in string.", ],
			["Unexpected carriage return character.", ],
			["Invalid numeric notation.", ],
			["Stray carriage return character in source code.", ],
		],
		"raw": [
			"Unexpected %DEBUG_NAME% in class body.",
			"Expected statement, found \"%NAME%\" instead.",
			"Parser bug: parsing literal node without literal token.",
			"Unexpected \"%NAME%\" in node path.",
			"Unexpected \"?\" in source. If you want a ternary operator, use \"truthy_value if true_condition else falsy_value\".",
			"Closing \"%TOKEN%\" doesn't have an opening counterpart.",
			"Closing \"%TOKEN%\" doesn't match the opening \"%TOKEN%\".",
			"Multiple underscores cannot be adjacent in a numeric literal.",
			"Cannot use a decimal point twice in a number.",
			"Cannot use a decimal point in a hexadecimal number.",
			"Cannot use a decimal point in a binary number.",
			"Multiple underscores cannot be adjacent in a numeric literal.",
			"Multiple underscores cannot be adjacent in a numeric literal.",
			"Cannot use a decimal point twice in a number.",
			"Invalid hexadecimal digit in unicode escape sequence.",
			"Invalid escape in string.",
			"Unexpected carriage return character.",
			"Invalid numeric notation.",
			"Stray carriage return character in source code.",
		],
		"code": ErrorCode.UNEXPECTED_CHARACTER,
	},
	{
		"patterns": [
			["Property with inline code must go to an indented block.", ],
			["Expected indented block after class declaration.", ],
			["Missing unindent at the end of the class body.", ],
			["Expected indented block for property after \":\".", ],
			["Expected end of indented block for property.", ],
			["Expected indented block after ", ".", ],
			["Missing unindent at the end of ", ".", ],
			["Expected an indented block after \"match\" statement.", ],
			["Unindent doesn't match the previous indentation level.", ],
			["Tokenizer bug: trying to dedent without previous indent.", ],
		],
		"raw": [
			"Property with inline code must go to an indented block.",
			"Expected indented block after class declaration.",
			"Missing unindent at the end of the class body.",
			"Expected indented block for property after \":\".",
			"Expected end of indented block for property.",
			"Expected indented block after %CONTEXT%.",
			"Missing unindent at the end of %CONTEXT%.",
			"Expected an indented block after \"match\" statement.",
			"Unindent doesn't match the previous indentation level.",
			"Tokenizer bug: trying to dedent without previous indent.",
		],
		"code": ErrorCode.INVALID_INDENTATION,
	},
	{
		"patterns": [
			["Static constructor must be declared static.", ],
			["Cannot call non-static function \"", "()\"  from the static function \"", "()\".", ],
			["Cannot call non-static function \"", "()\"  from a static variable initializer.", ],
			["Cannot call non-static function \"", "()\"  on the class \"", "\" directly. Make an instance instead.", ],
			["Cannot use shorthand \"get_node()\"  notation (\"$\") in a static function.", ],
			["Cannot use shorthand \"get_node()\"  notation (\"%\") in a static function.", ],
			["Cannot access ", " \"", "\" from the static function \"", "()\".", ],
			["Cannot access ", " \"", "\" from a static variable initializer.", ],
		],
		"raw": [
			"Static constructor must be declared static.",
			"Cannot call non-static function \"%FUNCTION_NAME%()\"  from the static function \"%NAME%()\".",
			"Cannot call non-static function \"%FUNCTION_NAME%()\"  from a static variable initializer.",
			"Cannot call non-static function \"%FUNCTION_NAME%()\"  on the class \"%CLASS%\" directly. Make an instance instead.",
			"Cannot use shorthand \"get_node()\"  notation (\"$\") in a static function.",
			"Cannot use shorthand \"get_node()\"  notation (\"%\") in a static function.",
			"Cannot access %SOURCE_TYPE% \"%NAME%\" from the static function \"%NAME%()\".",
			"Cannot access %SOURCE_TYPE% \"%NAME%\" from a static variable initializer.",
		],
		"code": ErrorCode.MISPLACED_STATIC_CALL,
	},
	{
		"patterns": [
			["Constructor cannot return a value.", ],
			["Not all code paths return a value.", ],
			["A void function cannot return a value.", ],
			["Cannot return value of type \"", "\" because the function return type is \"", "\".", ],
		],
		"raw": [
			"Constructor cannot return a value.",
			"Not all code paths return a value.",
			"A void function cannot return a value.",
			"Cannot return value of type \"%TYPE%\" because the function return type is \"%OTHER_TYPE%\".",
		],
		"code": ErrorCode.RETURN_VALUE_MISMATCH,
	},
	{
		"patterns": [
			["Expected iterable after \"in\".", ],
			["Expected \"in\" or \":\" after \"for\" variable name.", ],
			["Expected \"in\" after \"for\" variable type specifier.", ],
			["Expected \"in\" after \"not\" in content-test operator.", ],
		],
		"raw": [
			"Expected iterable after \"in\".",
			"Expected \"in\" or \":\" after \"for\" variable name.",
			"Expected \"in\" after \"for\" variable type specifier.",
			"Expected \"in\" after \"not\" in content-test operator.",
		],
		"code": ErrorCode.IN_EXPECTED_AFTER_IDENTIFIER,
	},
	{
		"patterns": [
			["Cannot call on an expression. Use \".call(\" if it's a Callable.", ],
			["Invalid operands \"", "\" and \"", "\" for assignment operator.", ],
			[" in operator ", ".", ],
			["Invalid operands to operator ", ", ", " and ", ".", ],
			["Invalid operands \"", "\" and \"", "\" for \"", "\" operator.", ],
			["Invalid operand of type \"", "\" for unary operator \"", "\".", ],
		],
		"raw": [
			"Cannot call on an expression. Use \".call(\" if it's a Callable.",
			"Invalid operands \"%ASSIGNEE%\" and \"%ASSIGNED%\" for assignment operator.",
			"%VALUE% in operator %OP%.",
			"Invalid operands to operator %OP%, %LEFT% and %RIGHT%.",
			"Invalid operands \"%LEFT%\" and \"%RIGHT%\" for \"%OP%\" operator.",
			"Invalid operand of type \"%TYPE%\" for unary operator \"%OP%\".",
		],
		"code": ErrorCode.INVALID_OPERATOR_USAGE,
	},
	{
		"patterns": [
			["Export type can only be built-in, a resource, a node, or an enum.", ],
			["Node export is only supported in Node-derived classes, but the current class inherits \"", "\".", ],
			["Export type can only be built-in, a resource, a node, or an enum.\", p_annotation)", ],
			["\"@export_tool_button\" annotation requires a variable of type \"Callable\", but type \"", "\" was given instead.", ],
			["Singleton ", " is not a GDScript.", ],
			["Constant \"", "\" is not a preloaded script or class.", ],
			["Cannot get nested types for extension from non-GDScript type \"", "\".", ],
			["Local constant \"", "\" is not a valid type.", ],
			["Variant only contains enum types, which do not have nested types.", ],
			["Built-in types only contain enum types, which do not have nested types.", ],
			["\"", "\" is a ", " but does not contain a type.", ],
			["Member \"", "\" under base \"", "\" is not a valid type.", ],
			["Only arrays and dictionaries can specify collection element types.", ],
			["Enum values must be integers.", ],
			["Cannot convert argument ", " of annotation \"", "\" from \"", "\" to \"", "\".", ],
			["The rest parameter type must be \"Array\", but \"", "\" is specified.", ],
			["Cannot assign a value of type ", " to ", " \"", "\" with specified type ", ".", ],
			["Unable to iterate on object of type \"", "\".", ],
			["Unable to iterate on value of type \"", "\".", ],
			["Unable to iterate on value of type \"", "\" with variable of type \"", "\".", ],
			["Expected string for assert error message.", ],
			["Cannot ", " a value of type \"", "\" as \"", "\".", ],
			["Failed to convert a value of type \"", "\" to \"", "\".", ],
			["Cannot have an element of type \"", "\" in an array of type \"Array[", "]\".", ],
			["Cannot have a key of type \"", "\" in a dictionary of type \"Dictionary[", ", ", "]\".", ],
			["Cannot have a value of type \"", "\" in a dictionary of type \"Dictionary[", ", ", "]\".", ],
			["Value of type \"", "\" cannot be assigned to a variable of type \"", "\".", ],
			["Expression is of type \"", "\" so it can't be of type \"", "\".", ],
		],
		"raw": [
			"Export type can only be built-in, a resource, a node, or an enum.",
			"Node export is only supported in Node-derived classes, but the current class inherits \"%BASE_CLASS%\".",
			"Export type can only be built-in, a resource, a node, or an enum.\", p_annotation)",
			"\"@export_tool_button\" annotation requires a variable of type \"Callable\", but type \"%IDENTIFIER%\" was given instead.",
			"Singleton %NAME% is not a GDScript.",
			"Constant \"%NAME%\" is not a preloaded script or class.",
			"Cannot get nested types for extension from non-GDScript type \"%BASE%\".",
			"Local constant \"%IDENTIFIER%\" is not a valid type.",
			"Variant only contains enum types, which do not have nested types.",
			"Built-in types only contain enum types, which do not have nested types.",
			"\"%IDENTIFIER%\" is a %TYPE_NAME% but does not contain a type.",
			"Member \"%NAME%\" under base \"%TO_STRING%\" is not a valid type.",
			"Only arrays and dictionaries can specify collection element types.",
			"Enum values must be integers.",
			"Cannot convert argument %IDX% of annotation \"%IDENTIFIER%\" from \"%TYPE%\" to \"%OTHER_TYPE%\".",
			"The rest parameter type must be \"Array\", but \"%TYPE%\" is specified.",
			"Cannot assign a value of type %TYPE% to %KIND% \"%NAME%\" with specified type %OTHER_TYPE%.",
			"Unable to iterate on object of type \"%TYPE%\".",
			"Unable to iterate on value of type \"%TYPE%\".",
			"Unable to iterate on value of type \"%TYPE%\" with variable of type \"%OTHER_TYPE%\".",
			"Expected string for assert error message.",
			"Cannot %USAGE% a value of type \"%TYPE%\" as \"%OTHER_TYPE%\".",
			"Failed to convert a value of type \"%TYPE%\" to \"%OTHER_TYPE%\".",
			"Cannot have an element of type \"%TYPE%\" in an array of type \"Array[%OTHER_TYPE%]\".",
			"Cannot have a key of type \"%TYPE%\" in a dictionary of type \"Dictionary[%KEY_TYPE%, %VALUE_TYPE%]\".",
			"Cannot have a value of type \"%TYPE%\" in a dictionary of type \"Dictionary[%KEY_TYPE%, %VALUE_TYPE%]\".",
			"Value of type \"%TYPE%\" cannot be assigned to a variable of type \"%OTHER_TYPE%\".",
			"Expression is of type \"%TYPE%\" so it can't be of type \"%OTHER_TYPE%\".",
		],
		"code": ErrorCode.TYPE_MISMATCH,
	},
	{
		"patterns": [
			["Expected \"else\" after ternary operator condition.", ],
		],
		"raw": [
			"Expected \"else\" after ternary operator condition.",
		],
		"code": ErrorCode.INCOMPATIBLE_TERNARY,
	},
	{
		"patterns": [
			["Function \"", "\" cannot be used as getter because of its signature.", ],
			["Function with return type \"", "\" cannot be used as getter for a property of type \"", "\".", ],
			["Function \"", "\" cannot be used as setter because of its signature.", ],
			["Function with argument type \"", "\" cannot be used as setter for a property of type \"", "\".", ],
			["Getter with type \"", "\" cannot be used along with setter of type \"", "\".", ],
			["Class \"", "\" must implement \"", "()\"  and other inherited abstract methods or be marked as \"@abstract\".", ],
			["The function signature doesn't match the parent. Parent signature is \"", "\".", ],
			["No constructor of \"", "\" matches the signature \"", "\".", ],
		],
		"raw": [
			"Function \"%NAME%\" cannot be used as getter because of its signature.",
			"Function with return type \"%TYPE%\" cannot be used as getter for a property of type \"%VAR_TYPE%\".",
			"Function \"%NAME%\" cannot be used as setter because of its signature.",
			"Function with argument type \"%TYPE%\" cannot be used as setter for a property of type \"%PROP_TYPE%\".",
			"Getter with type \"%TYPE%\" cannot be used along with setter of type \"%GET_TYPE%\".",
			"Class \"%CLASS_NAME%\" must implement \"%NAME%()\"  and other inherited abstract methods or be marked as \"@abstract\".",
			"The function signature doesn't match the parent. Parent signature is \"%SIGNATURE%\".",
			"No constructor of \"%TYPE%\" matches the signature \"%SIGNATURE%\".",
		],
		"code": ErrorCode.SIGNATURE_MISMATCH,
	},
	{
		"patterns": [
			["Cannot assign a new value to a constant.", ],
			["Cannot assign a new value to a read-only property.", ],
		],
		"raw": [
			"Cannot assign a new value to a constant.",
			"Cannot assign a new value to a read-only property.",
		],
		"code": ErrorCode.CANT_ASSIGN_TO_CONSTANT,
	},
	{
		"patterns": [
			["Cannot get return value of call to \"", "()\"  because it returns \"void\".", ],
		],
		"raw": [
			"Cannot get return value of call to \"%FUNCTION_NAME%()\"  because it returns \"void\".",
		],
		"code": ErrorCode.VOID_ASSIGNMENT,
	},
	{
		"patterns": [
			["Cannot call the parent class' virtual function \"", "()\"  because it hasn't been defined.", ],
			["Cannot call the parent class' abstract function \"", "()\"  because it hasn't been defined.", ],
			["Enums only have Dictionary built-in methods. Function \"", "()\"  does not exist for enum \"", "\".", ],
			["The native enum \"", "\" does not behave like Dictionary and does not have methods of its own.", ],
			["Function \"", "()\"  not found in base ", ".", ],
			["Function \"", "()\"  not found in base ", ".", ],
			["Static function \"", "()\"  not found in base \"", "\".", ],
			["Cannot use shorthand \"get_node()\"  notation (\"$\") on a class that isn't a node.", ],
			["Cannot use shorthand \"get_node()\"  notation (\"%\") on a class that isn't a node.", ],
			["Cannot call function on enum value.", ],
			["Cannot call non-const Dictionary function \"", "()\"  on enum \"", "\".", ],
		],
		"raw": [
			"Cannot call the parent class' virtual function \"%FUNCTION_NAME%()\"  because it hasn't been defined.",
			"Cannot call the parent class' abstract function \"%FUNCTION_NAME%()\"  because it hasn't been defined.",
			"Enums only have Dictionary built-in methods. Function \"%FUNCTION_NAME%()\"  does not exist for enum \"%ENUM_TYPE%\".",
			"The native enum \"%ENUM_TYPE%\" does not behave like Dictionary and does not have methods of its own.",
			"Function \"%FUNCTION_NAME%()\"  not found in base %BASE_NAME%.%NAME%",
			"Function \"%FUNCTION_NAME%()\"  not found in base %BASE_NAME%.",
			"Static function \"%FUNCTION_NAME%()\"  not found in base \"%BASE_NAME%\".",
			"Cannot use shorthand \"get_node()\"  notation (\"$\") on a class that isn't a node.",
			"Cannot use shorthand \"get_node()\"  notation (\"%\") on a class that isn't a node.",
			"Cannot call function on enum value.",
			"Cannot call non-const Dictionary function \"%FUNCTION%()\"  on enum \"%ENUM_TYPE%\".",
		],
		"code": ErrorCode.UNSAFE_METHOD_ACCESS,
	},
	{
		"patterns": [
			["Name \"", "\" is a Callable. You can call it with \"", ".call()\"  instead.", ],
		],
		"raw": [
			"Name \"%FUNCTION_NAME%\" is a Callable. You can call it with \"%FUNCTION_NAME%.call()\"  instead.",
		],
		"code": ErrorCode.FUNCTION_USED_AS_PROPERTY,
	},
	{
		"patterns": [
			["Name \"", "\" called as a function but is a \"", "\".", ],
			["Member \"", "\" is not a function.", ],
		],
		"raw": [
			"Name \"%FUNCTION_NAME%\" called as a function but is a \"%KIND%\".",
			"Member \"%FUNCTION_NAME%\" is not a function.",
		],
		"code": ErrorCode.PROPERTY_USED_AS_FUNCTION,
	},
	{
		"patterns": [
			["Function \"", "()\"  is a coroutine, so it must be called with \"await\".", ],
		],
		"raw": [
			"Function \"%FUNCTION_NAME%()\"  is a coroutine, so it must be called with \"await\".",
		],
		"code": ErrorCode.FUNCTION_MAY_YIELD,
	},
	{
		"patterns": [
			["Invalid cast. Cannot convert from \"", "\" to \"", "\".", ],
		],
		"raw": [
			"Invalid cast. Cannot convert from \"%TYPE%\" to \"%OTHER_TYPE%\".",
		],
		"code": ErrorCode.UNSAFE_CAST,
	},
	{
		"patterns": [
			["Cannot get property from enum value.", ],
			["Cannot find member \"", "\" in base \"", "\".", ],
			["Cannot get property \"", "\" on a null object.", ],
		],
		"raw": [
			"Cannot get property from enum value.",
			"Cannot find member \"%NAME%\" in base \"%BASE%\".%TYPE%",
			"Cannot get property \"%NAME%\" on a null object.",
		],
		"code": ErrorCode.UNSAFE_PROPERTY_ACCESS,
	},
	{
		"patterns": [
			["Cannot use another enum element before it was declared.", ],
		],
		"raw": [
			"Cannot use another enum element before it was declared.",
		],
		"code": ErrorCode.UNASSIGNED_VARIABLE,
	},
	{
		"patterns": [
			["Cannot get index \"", "\" from \"", "\".", ],
			["Invalid index type \"", "\" for a base of type \"", "\".", ],
			["Only \"String\" or \"StringName\" can be used as index for type \"", "\", but received \"", "\".", ],
			["Cannot use subscript operator on a base of type \"", "\".", ],
		],
		"raw": [
			"Cannot get index \"%IDX%\" from \"%SUBSCRIPT%\".",
			"Invalid index type \"%TYPE%\" for a base of type \"%OTHER_TYPE%\".",
			"Only \"String\" or \"StringName\" can be used as index for type \"%TYPE%\", but received \"%OTHER_TYPE%\".",
			"Cannot use subscript operator on a base of type \"%TYPE%\".",
		],
		"code": ErrorCode.CANT_GET_INDEX,
	},
	{
		"patterns": [
			["Invisible text direction control character present in the string, use regular string literal instead of r-string.", ],
			["Invisible text direction control character present in the string, escape it (\"", "\") to avoid confusion.", ],
			["Invalid UTF-16 sequence in string, unpaired lead surrogate.", ],
			["Invalid UTF-16 sequence in string, unpaired trail surrogate.", ],
			["Invalid white space character U+", ".", ],
			["Invalid character \"", "\" (U+", ").", ],
		],
		"raw": [
			"Invisible text direction control character present in the string, use regular string literal instead of r-string.",
			"Invisible text direction control character present in the string, escape it (\"%STRING%\") to avoid confusion.",
			"Invalid UTF-16 sequence in string, unpaired lead surrogate.",
			"Invalid UTF-16 sequence in string, unpaired trail surrogate.",
			"Invalid white space character U+%CODE%.",
			"Invalid character \"%CHARA%\" (U+%CODE%).",
		],
		"code": ErrorCode.UNKNOWN_CHARACTER,
	},
	{
		"patterns": [
			["Mixed use of tabs and spaces for indentation.", ],
			["Used ", " character for indentation instead of ", " as used before in the file.", ],
		],
		"raw": [
			"Mixed use of tabs and spaces for indentation.",
			"Used %CHARA% character for indentation instead of %OTHER_CHARA% as used before in the file.",
		],
		"code": ErrorCode.SPACES_BEFORE_TABS,
	},
]
